In [14]:
import numpy as np
from scipy.optimize import minimize
from scipy.linalg import eig

# Definir el Hamiltoniano H como una matriz
H = np.array([
    [-1, 0, 0, 1, 0],
    [0, -1, 1, 0, 0],
    [0, 1, -2, 1, 0],
    [1, 0, -1, -3, 1],
    [0, 0, 0, 1, -1],
  ])

# Paso 1: Verificar los términos off-diagonales
off_diagonal_terms = H - np.diag(np.diagonal(H))
print("Términos off-diagonales de H:\n", off_diagonal_terms)

# Paso 2: Encontrar el estado fundamental
# Utilizando un método de diagonalización para encontrar autovalores y autovectores
eigenvalues, eigenvectors = eig(H)
ground_state_index = np.argmin(eigenvalues)
ground_state = eigenvectors[:, ground_state_index]
print("Estado fundamental (vector):\n", ground_state)
print("Valor de energía mínima (autovalor):\n", eigenvalues[ground_state_index])

# Paso 3: Convertir el estado fundamental en bitstrings óptimos
# En este ejemplo simplificado, interpretaremos el estado fundamental directamente.
# En un contexto más complejo, podríamos necesitar un mapeo adicional.
optimal_bitstrings = np.round(np.abs(ground_state))
print("Bitstrings óptimos:\n", optimal_bitstrings)

# Verificar la sumatoria de los términos off-diagonales
# Aquí simplemente sumamos los términos off-diagonales como ejemplo
sum_off_diagonal = np.sum(off_diagonal_terms)
print("Sumatoria de los términos off-diagonales:\n", sum_off_diagonal)

Términos off-diagonales de H:
 [[ 0  0  0  1  0]
 [ 0  0  1  0  0]
 [ 0  1  0  1  0]
 [ 1  0 -1  0  1]
 [ 0  0  0  1  0]]
Estado fundamental (vector):
 [-0.23633867-0.13560789j  0.28645039-0.07168674j -0.64250073-0.j
  0.42722464+0.4110817j  -0.23633867-0.13560789j]
Valor de energía mínima (autovalor):
 (-3.1107769895788078-0.5282405895199751j)
Bitstrings óptimos:
 [0. 0. 1. 1. 0.]
Sumatoria de los términos off-diagonales:
 6


In [18]:
eigenvalues[ground_state_index]

(-3.1107769895788078-0.5282405895199751j)